name = "Glo"
uuid = "578b42c6-ccb1-11e9-3f90-91546bb1a07d"
authors = ["Simon Christ"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
